---
- hosts: webserver
  become: yes
  vars:
    db_name: "{{ lookup('env', 'DB_NAME') }}"
    db_user: "{{ lookup('env', 'DB_USER') }}"
    db_password: "{{ lookup('env', 'DB_PASSWORD') }}"
    ec2_instance_ip: "{{ lookup('env', 'EC2_INSTANCE_IP') }}"
    rds_endpoint: "{{ lookup('env', 'RDS_ENDPOINT') }}"
    efs_id: "{{ lookup('env', 'EFS_ID') }}"
    aws_region: "{{ lookup('env', 'AWS_REGION') }}"
    efs_mount_point: /mnt/efs  # Define the mount point for the EFS
  tasks:
    - name: Install necessary packages
      yum:
        name:
          - httpd
          - php
          - php-mysqlnd
          - mysql-server
          - amazon-efs-utils
        state: present

    - name: Install Botocore
      pip:
        name: botocore
        state: present

    - name: Start and enable MySQL
      service:
        name: mysqld
        state: started
        enabled: yes

    - name: Download WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes

    - name: Create EFS mount point directory
      file:
        path: "{{ efs_mount_point }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Mount EFS
      command: "mount -t efs -o tls {{ efs_id }}:/ {{ efs_mount_point }}"
      args:
        creates: "{{ efs_mount_point }}/lost+found"

    - name: Move wp-content to EFS
      command: "mv /var/www/html/wordpress/wp-content {{ efs_mount_point }}/"

    - name: Create symlink for wp-content
      file:
        src: "{{ efs_mount_point }}/wp-content"
        dest: /var/www/html/wordpress/wp-content
        state: link

    - name: Configure WordPress
      template:
        src: templates/wp-config.php.j2
        dest: /var/www/html/wordpress/wp-config.php

    - name: Ensure Apache is running and enabled
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Debug EFS ID
      debug:
        msg: "Mounting EFS with ID {{ efs_id }}"
