---
- hosts: webserver
  become: yes
  vars:
    db_name: "{{ lookup('env', 'DB_NAME') }}"
    db_user: "{{ lookup('env', 'DB_USER') }}"
    db_password: "{{ lookup('env', 'DB_PASSWORD') }}"
    ec2_instance_ip: "{{ lookup('env', 'EC2_INSTANCE_IP') }}"
    rds_endpoint: "{{ lookup('env', 'RDS_ENDPOINT') }}"
    efs_id: "{{ lookup('env', 'EFS_ID') }}"
    aws_region: "{{ lookup('env', 'AWS_REGION') }}"
    ec2_instance_az: "{{ lookup('env', 'EC2_INSTANCE_AZ') }}"
    efs_mount_point: /mnt/efs  # Define the mount point for the EFS
  tasks:
    - name: Install Amazon EFS Utilities
      yum:
        name: amazon-efs-utils
        state: present

    - name: Create a directory for mounting EFS
      file:
        path: "{{ efs_mount_point }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Install Botocore
      pip:
        name: botocore
        state: present

    - name: Mount the EFS file system
      command: "mount -t efs -o tls,az={{ ec2_instance_az }} {{ efs_id }}:/ {{ efs_mount_point }}"
      args:
        creates: "{{ efs_mount_point }}/lost+found"  # Only run if not already mounted

    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Ensure Apache is running and enabled
      service:
        name: httpd
        state: started
        enabled: yes
