name: Deploy Infrastructure and Configure WordPress

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with: 
          terraform_version: 1.4.0

      - name: Terraform Init and Apply
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve
        env:
          TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_db_name: ${{ secrets.DB_NAME }}

      - name: Capture Terraform Outputs
        id: terraform-outputs
        run: |
          cd terraform
          echo "::set-output name=ec2_instance_ip::$(terraform output -raw ec2_instance_ip)"
          echo "::set-output name=rds_endpoint::$(terraform output -raw rds_endpoint)"
          echo "::set-output name=efs_id::$(terraform output -raw efs_id)"

      - name: Run Ansible
        run: |
          cd ansible
          ansible-playbook -i inventory.ini setup.yml
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          EC2_INSTANCE_IP: ${{ steps.terraform-outputs.outputs.ec2_instance_ip }}
          RDS_ENDPOINT: ${{ steps.terraform-outputs.outputs.rds_endpoint }}
          EFS_ID: ${{ steps.terraform-outputs.outputs.efs_id }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
