name: Deploy Infrastructure and Configure WordPress

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_BASE64 }}" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with: 
          terraform_version: 1.4.0
          terraform_wrapper: false

      - name: Terraform Init and Apply
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve
        env:
          TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_db_name: ${{ secrets.DB_NAME }}

      - name: Capture Terraform Outputs
        id: terraform-outputs
        run: |
          cd terraform
          echo "ec2_instance_ip=$(terraform output -raw ec2_instance_ip)" >> $GITHUB_ENV
          echo "rds_endpoint=$(terraform output -raw rds_endpoint)" >> $GITHUB_ENV
          echo "efs_id=$(terraform output -raw efs_id)" >> $GITHUB_ENV

      - name: Print Captured Outputs
        run: |
          echo "Captured EC2 Instance IP: ${{ env.ec2_instance_ip }}"
          echo "Captured RDS Endpoint: ${{ env.rds_endpoint }}"
          echo "Captured EFS ID: ${{ env.efs_id }}"

      - name: Run Ansible
        run: |
          cd ansible
          ansible-playbook -i inventory.ini setup.yml --private-key ~/.ssh/id_rsa
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          EC2_INSTANCE_IP: ${{ env.ec2_instance_ip }}
          RDS_ENDPOINT: ${{ env.rds_endpoint }}
          EFS_ID: ${{ env.efs_id }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
